#!/bin/sh
echo "Now it is time to setup your Databases & Admin passwords"
read -p "Press Enter to Continue, or CTRL-C to abort."
setenforce 0
sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/selinux/config
/etc/rc.d/init.d/elastix-firstboot start
echo "Now we are running some cleanup, and making sure everything is up to date"
rm -rf /etc/yum.repos.d/elastix-cd.repo /mnt/iso/ Elastix-4.0.74-Stable-x86_64-bin-10Feb2016.iso
mv /etc/yum.repos.d/elastix.repo.rpmnew /etc/yum.repos.d/elastix.repo
yum clean all
yum -y update
cp /etc/sysconfig/iptables /etc/sysconfig/iptables.orgelastix
echo '# Generated by iptables-save v1.4.21 on Fri Mar 11 13:15:37 2016
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Fri Mar 11 13:15:37 2016
# Generated by iptables-save v1.4.21 on Fri Mar 11 13:15:37 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:ELASTIX_FORWARD - [0:0]
:ELASTIX_INPUT - [0:0]
:ELASTIX_OUTPUT - [0:0]
-A INPUT -j ELASTIX_INPUT
-A FORWARD -j ELASTIX_FORWARD
-A OUTPUT -j ELASTIX_OUTPUT
-A ELASTIX_FORWARD -j REJECT --reject-with icmp-port-unreachable
-A ELASTIX_INPUT -i lo -j ACCEPT
-A ELASTIX_INPUT -p icmp -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --dport 67:68 -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --dport 5004:5082 -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --dport 4569 -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --dport 5036 -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --dport 10000:20000 -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --dport 2727 -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --sport 53 -j ACCEPT
-A ELASTIX_INPUT -p udp -m udp --dport 69 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 25 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 110 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 143 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 993 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 995 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 5222 -j ACCEPT
-A ELASTIX_INPUT -p tcp -m tcp --dport 9090 -j ACCEPT
-A ELASTIX_INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A ELASTIX_INPUT -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Fri Mar 11 13:15:37 2016
# Generated by iptables-save v1.4.21 on Fri Mar 11 13:15:37 2016
*mangle
:PREROUTING ACCEPT [2915:315121]
:INPUT ACCEPT [2915:315121]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3972:3598372]
:POSTROUTING ACCEPT [3972:3598372]
COMMIT
# Completed on Fri Mar 11 13:15:37 2016
' > /etc/sysconfig/iptables
systemctl restart iptables
echo " "
echo "Note: The NetworkManager was not installed, as it breaks the Virtual Network"
echo "interfaces that OpenVZ uses to provide Internet / Network access. " 
echo ""
echo "Now we need another reeboot to finish the setup."
read -p "Press Enter to Reboot, or CTRL-C to abort."
reboot
